let service = {
    emojis: [
        {
            title: 'Smileys & People',
            icon: '😊',
            data: [
                {icon: '😁', description: 'happy smile'},
                {icon: '😂', description: 'happy smile'},
                {icon: '🤣', description: 'happy smile'},
                {icon: '😃', description: 'happy smile'},
                {icon: '😄', description: 'happy smile'},
                {icon: '😆', description: 'happy smile'},
                {icon: '🙂', description: 'happy smile'},
                {icon: '😉', description: 'happy smile'},
                {icon: '😊', description: 'happy smile'},
                {icon: '😋', description: 'happy smile'},
                {icon: '😎', description: 'attitude proud'},
                {icon: '😍', description: 'happy heart  love'},
                {icon: '😘', description: 'happy heart  love kiss'},
                {icon: '😗', description: 'happy love kiss'},
                {icon: '😙', description: 'happy love kiss'},
                {icon: '😚', description: 'happy love kiss pout'},
                {icon: '🙂', description: 'happy love kiss pout'},
                {icon: '🤗', description: 'happy naughty'},
                {icon: '🤩', description: 'happy'},
                {icon: '🤔', description: ''},
                {icon: '🤨', description: 'funny'},
                {icon: '😐', description: 'sad speechless'},
                {icon: '😑', description: 'sad speechless'},
                {icon: '😶', description: 'sad speechless'},
                {icon: '🙄', description: 'sad speechless'},
                {icon: '😏', description: 'prudy'},
                {icon: '😣', description: 'sad '},
                {icon: '😥', description: 'sad '},
                {icon: '😮', description: 'shocked'},
                {icon: '🤐', description: 'speechless'},
                {icon: '😯', description: ' Speechless Face'},
                {icon: '😪', description: 'Sleepy Face'},
                {icon: '😫', description: 'Tired Face'},
                {icon: '😴', description: 'Sleeping Face'},
                {icon: '😌', description: 'Relieved Face'},
                {icon: '😛', description: 'Face With Stuck-Out Tongue'},
                {icon: '😜', description: 'Face With Stuck-Out Tongue & Winking Eye'},
                {icon: '😝', description: 'Face With Stuck-Out Tongue & Tightly Closed Eyes'},
                {icon: '🤤', description: 'Drooling Face'},
                {icon: '😒', description: 'Unamused Face'},
                {icon: '😓', description: 'Face With Cold Sweat'},
                {icon: '😔', description: 'Pensive Face'},
                {icon: '😕', description: 'Confused Face'},
                {icon: '🙃', description: 'Upside-Down Face'},
                {icon: '🤑', description: 'Money-Mouth Face'},
                {icon: '😲', description: 'Astonished Face'},
                {icon: '☹️', description: 'Frowning Face'},
                {icon: '🙁', description: 'Slightly Frowning Face'},
                {icon: '😖', description: 'Confounded Face'},
                {icon: '😞', description: 'Disappointed Face'},
                {icon: '😟', description: 'Worried Face'},
                {icon: '😤', description: 'Face With Look of Triumph'},
                {icon: '😢', description: 'Crying Face'},
                {icon: '😭', description: 'Loudly Crying Face'},
                {icon: '😦', description: 'Frowning Face With Open Mouth'},
                {icon: '😧', description: 'Anguished Face'},
                {icon: '😨', description: 'Fearful Face'},
                {icon: '😩', description: 'Weary Face'},
                {icon: '🤯', description: 'Face With Exploding Head'},
                {icon: '😬', description: 'Grimacing Face'},
                {icon: '😰', description: 'Anxious Face with Sweat'},
                {icon: '😱', description: 'Face Screaming in Fear'},
                {icon: '😳', description: 'Flushed Face'},
                {icon: '🤪', description: 'Zany Face'},
                {icon: '❤️', description: 'heart'},
                {icon: '💛', description: 'heart'},
                {icon: '💚', description: 'heart'},
                {icon: '💙', description: 'heart'},
                {icon: '💔', description: 'heart'},
                {icon: '💜', description: 'heart'},
                {icon: '❣', description: 'heart'},
                {icon: '💕', description: 'heart'},
                {icon: '💓', description: 'heart'},
                {icon: '💞', description: 'heart'},
                {icon: '💗', description: 'heart'},
                {icon: '💘', description: 'heart'},
                {icon: '💖', description: 'heart'},
                {icon: '💝', description: 'heart'},
                {icon: '😵', description: 'Dizzy Face'},
                {icon: '😡', description: 'Angry Face'},
                {icon: '😞', description: 'sad'},
                {icon: '😰', description: 'sad'},
                {icon: '😪', description: 'sad'},
                {icon: '😓', description: 'sad'},
                {icon: '😢', description: 'sad'},
                {icon: '😥', description: 'sad'},
                {icon: '😧', description: 'sad'},
                {icon: '😦', description: 'sad'},
                {icon: '😭', description: 'sad'},
                {icon: '😵', description: 'sad'},
                {icon: '😿', description: 'sad'},
                {icon: '🙀', description: 'sad'},
                {icon: '🙍‍', description: 'sad'},
                {icon: '😡', description: 'Pouting Face'},
                {icon: '🤬', description: 'Face With Symbols Over The Mouth'},
                {icon: '😷', description: 'Face With Medical Mask'},
                {icon: '🤒', description: 'Face With Thermometer'},
                {icon: '🤕', description: 'Face With Head Bandage'},
                {icon: '🤢', description: ' Nauseated Face'},
                {icon: '🤮', description: 'Face With Open Mouth, Throwing Up'},
                {icon: '🤧', description: 'Sneezing Face'},
                {icon: '😇', description: 'Smiling Face with Halo'},
                {icon: '🤠', description: 'Face With Cowboy Hat'},
                {icon: '🤡', description: 'Clown Face'},
                {icon: '🤥', description: 'Lying Face'},
                {icon: '🤫', description: 'Exhorting Face'},
                {icon: '🤭', description: 'Face With Hand Over The Mouth'},
                {icon: '🧐', description: 'Face With Monocle'},
                {icon: '🤓', description: 'Nerd Face'},
                {icon: '😈', description: 'Smiling Face With Horns'},
                {icon: '👿', description: 'Goblin'},
                {icon: '👹', description: 'Japanese Ogre “Namahage“'},
                {icon: '👺', description: 'Japanese Goblin'},
                {icon: '💀', description: 'Skull'},
                {icon: '☠️', description: 'Skull and Crossbones'},
                {icon: '👻', description: 'Ghost'},
                {icon: '👽', description: 'Alien'},
                {icon: '👾', description: 'Alien Monster'},
                {icon: '🤖', description: 'Robot Face'},
                {icon: '💩', description: 'Pile of Poo'},
                {icon: '😺', description: 'Smiling Cat Face With Open Mouth'},
                {icon: '😸', description: 'Grinning Cat Face With Smiling Eyes'},
                {icon: '😹', description: 'Cat Face With Tears of Joy'},
                {icon: '😻', description: 'Smiling Cat Face With Heart-Eyes'},
                {icon: '😼', description: 'Cat Face With Wry Smile'},
                {icon: '😽', description: 'Kissing Cat Face With Closed Eyes'},
                {icon: '🙀', description: 'Weary Cat Face'},
                {icon: '😿', description: 'Crying Cat Face'},
                {icon: '😾', description: 'Pouting Cat Face'},
                {icon: '🙈', description: 'See-No-Evil Monkey'},
                {icon: '🙉', description: 'Hear-No-Evil Monkey'},
                {icon: '🙊', description: 'Speak-No-Evil Monkey'},
                {icon: '👶', description: 'Baby'},
                {icon: '🧒', description: 'Child'},
                {icon: '👦', description: 'Boy'},
                {icon: '👧', description: 'Girl'},
                {icon: '🧑', description: 'Adult'},
                {icon: '👨', description: 'Man'},
                {icon: '👩', description: 'Woman'},
                {icon: '🧓', description: 'Older Person'},
                {icon: '👴', description: 'Old Man'},
                {icon: '👵', description: 'Old woman'},
                {icon: '👨‍⚕️', description: 'Male Health Worker'},
                {icon: '👩‍⚕️', description: 'Female Health Worker'},
                {icon: '👨‍🎓', description: 'Male student'},
                {icon: '👩‍🎓', description: 'Female student'},
                {icon: '👨‍🏫', description: 'Male teacher'},
                {icon: '👩‍🏫', description: 'Female teacher'},
                {icon: '👨‍⚖️', description: 'Male Judge'},
                {icon: '👩‍⚖️', description: 'Female Judge'},
                {icon: '👨‍🌾', description: 'Male Farmer'},
                {icon: '👩‍🌾', description: 'Female Farmer'},
                {icon: '👨‍🍳', description: 'Male cook'},
                {icon: '👩‍🍳', description: 'Female cook'},
                {icon: '👨‍🔧', description: 'Male mechanic'},
                {icon: '👩‍🔧', description: 'Female mechanic'},
                {icon: '👨‍🏭', description: 'Male factory worker'},
                {icon: '👩‍🏭', description: 'Female factory worker'},
                {icon: '👨‍💼', description: 'Male Office Worker'},
                {icon: '👩‍💼', description: 'Female Office Worker'},
                {icon: '👩‍🔬', description: 'Female Scientist'},
                {icon: '👨‍💻', description: 'Male technologist'},
                {icon: '👩‍💻', description: 'Female technologist'},
                {icon: '👨‍🎤', description: 'Male Singer'},
                {icon: '👩‍🎤', description: 'Female Singer'},
                {icon: '👨‍🎨', description: 'Male Artist'},
                {icon: '👩‍🎨', description: 'Female Artist'},
                {icon: '👨‍✈️', description: 'Male Pilot'},
                {icon: '👩‍✈️', description: 'Female Pilot'},
                {icon: '👨‍🚀', description: 'Male Astronaut'},
                {icon: '👩‍🚀', description: 'Female Astronaut'},
                {icon: '👨‍🚒', description: 'male firefighter'},
                {icon: '👩‍🚒', description: 'Female firefighter'},
                {icon: '👮', description: 'Male Police Officer'},
                {icon: '👮', description: 'Female Police Officer'},
                {icon: '🕵️', description: 'Detective'},
                {icon: '💂', description: 'Guard'},
                {icon: '👷', description: 'Construction Worker'},
                {icon: '🤴', description: 'Prince'},
                {icon: '👸', description: 'Princesses'},
                {icon: '👳', description: 'Man with Turban'},
                {icon: '👲', description: 'Man in Chinese Cap'},
                {icon: '🧕', description: 'Woman with HeadScarf'},
                {icon: '🧔', description: 'Man with Beard'},
                {icon: '👱', description: 'Man with Blonde Hairs'},
                {icon: '🤵', description: 'Man in Tuxedo'},
                {icon: '👰', description: 'Bride'},
                {icon: '🤰', description: 'Pregnant woman'},
                {icon: '🤱', description: 'Breastfeeding'},
                {icon: '👼', description: 'Baby Angel'},
                {icon: '🎅', description: 'Santa Claus'},
                {icon: '🤶', description: 'Mary Christmas'},
                {icon: '🧙', description: 'Magician'},
                {icon: '🧚', description: 'Woman Fairy'},
                {icon: '🧛', description: 'Vampire'},
                {icon: '🧜', description: 'Mermaid'},
                {icon: '🧝', description: 'Elf'},
                {icon: '🧞', description: 'Genie'},
                {icon: '🧟', description: 'Zombie'},
                {icon: '🙍', description: 'Frowning Person'},
                {icon: '🙎', description: 'Pouting person'},
                {icon: '🙅', description: 'Face With No Good Gesture'},
                {icon: '🙆', description: 'Face With Ok Gesture'},
                {icon: '💁', description: 'Information Desk Person'},
                {icon: '🙋', description: 'Happy Person Raising One Hand'},
                {icon: '🙇', description: 'Person Bowing Deeply'},
                {icon: '🤦', description: 'Woman Grabbing His Head'},
                {icon: '🤷', description: 'Person Shrugs'},
                {icon: '💆', description: 'Person is being massaged'},
                {icon: '💇', description: 'Person at the hairdresser\'s'},
                {icon: '🚶', description: 'Pedestrian'},
                {icon: '🏃', description: 'Running'},
                {icon: '💃', description: 'Dancing'},
                {icon: '🕺', description: 'Dancing Man'},
                {icon: '👯', description: 'Women With Bunny Ears'},
                {icon: '🧖', description: 'Person in Steaming room'},
                {icon: '🧗', description: 'Person Climbing'},
                {icon: '🧘', description: 'Person in lotus position'},
                {icon: '🛀', description: 'Person Taking Bath'},
                {icon: '🛌', description: 'Person Sleeping'},
                {icon: '🕴️', description: 'Man in Suit'},
                {icon: '🗣️', description: 'Person Speaking'},
                {icon: '👤', description: 'Silhouette of a Bust'},
                {icon: '👥', description: 'Silhouette Of Two Busts'},
                {icon: '🤺', description: 'Person Fencing'},
                {icon: '🏇', description: 'Horse Racing'},
                {icon: '⛷️', description: 'Skier'},
                {icon: '🏂', description: 'person snowboarding'},
                {icon: '🏌️', description: 'person Golfing'},
                {icon: '🏄', description: 'person surfing'},
                {icon: '🚣', description: 'Person Rowing Boat'},
                {icon: '🏊', description: 'person swimming'},
                {icon: '⛹️', description: 'Person Bouncing Ball'},
                {icon: '🏋️', description: 'Person Lifting Weights'},
                {icon: '🚴‍', description: 'Person Biking'},
                {icon: '🚵‍', description: 'Person Mountain Biking'},
                {icon: '🏎️', description: 'Person in a Racing Car'},
                {icon: '🏍️', description: 'Person on Motorcycle'},
                {icon: '🤸', description: 'Person Cartwheeling'},
                {icon: '🤼', description: 'People Wrestling'},
                {icon: '🤽', description: 'Person Playing Water Polo'},
                {icon: '🤾', description: 'Person Playing Handball'},
                {icon: '🤹', description: 'Person Juggling'},
                {icon: '👫', description: 'Man and Woman Holding Hands'},
                {icon: '💏', description: 'Couple with heart'},
                {icon: '👩‍❤️‍', description: 'kiss woman'},
                {icon: '💋‍👩‍‍', description: 'kiss woman'},
                {icon: '👨‍👩', description: 'Couple'},
                {icon: '👪', description: 'Family'},
                {icon: '👧', description: 'Girl'},
                {icon: '💪', description: 'Flexed Biceps'},
                {icon: '👈', description: 'Backhand Index Pointing Left'},
                {icon: '👉', description: 'Backhand Index Pointing Right'},
                {icon: '☝️', description: 'Index Pointing Up'},
                {icon: '👆', description: 'Backhand Index Pointing Up'},
                {icon: '👇', description: 'Backhand Index Pointing down'},
                {icon: '✌️', description: 'Victory Hand'},
                {icon: '🤞', description: 'Crossed Fingers'},
                {icon: '🖖', description: 'Vulcan Salute'},
                {icon: '🤘', description: 'Sign of the Horns'},
                {icon: '🤙', description: 'Call Me Hand'},
                {icon: '🖐️', description: 'Hand with Fingers Splayed'},
                {icon: '✋', description: 'Raised Hand'},
                {icon: '👌', description: 'OK Hand'},
                {icon: '👍', description: 'Thumbs Up'},
                {icon: '👎', description: 'Thumbs Down'},
                {icon: '✊', description: 'Raised Fist'},
                {icon: '👊', description: 'Oncoming Fist'},
                {icon: '🤛', description: 'Left-Facing Fist'},
                {icon: '🤜', description: 'Right-Facing Fist'},
                {icon: '🤚', description: 'Raised Back of Hand'},
                {icon: '👋', description: 'Waving Hand'},
                {icon: '🤟', description: ' Love-You Gesture'},
                {icon: '✍️', description: 'Writing Hand'},
                {icon: '👏', description: 'Clapping Hands'},
                {icon: '👐', description: 'Open Hands'},
                {icon: '🙌', description: 'Raising Hands'},
                {icon: '🤲', description: 'Palms Up Together'},
                {icon: '🙏', description: 'Folded Hands'},
                {icon: '🤝', description: ''},
                {icon: '💅', description: 'Nail Polish'},
                {icon: '👂', description: 'Handshake'},
                {icon: '👃', description: 'Nose'},
                {icon: '👣', description: 'Footprints'},
                {icon: '👀', description: 'Eyes'},
                {icon: '👁️', description: 'Eye'},
                {icon: '🧠', description: 'Brain'},
                {icon: '👅', description: 'Tongue'},
                {icon: '👄', description: 'Mouth'},
                {icon: '💋', description: 'Kiss mark'},
                {icon: '💘', description: 'Heart with Arrow'},
                {icon: '❤️', description: 'Red Heart'},
                {icon: '💓', description: 'Beating Heart'},
                {icon: '💔', description: 'Broken Heart'},
                {icon: '💕', description: 'Two Hearts'},
                {icon: '💖', description: 'Sparkling Heart'},
                {icon: '💗', description: 'Growing Heart'},
                {icon: '💙', description: 'Blue Heart'},
                {icon: '💚', description: 'Green Heart'},
                {icon: '💛', description: 'Yellow Heart'},
                {icon: '🧡', description: 'Orange Heart'},
                {icon: '💜', description: 'Purple Heart'},
                {icon: '🖤', description: 'Black Heart'},
                {icon: '💝', description: 'Heart with Ribbon'},
                {icon: '💞', description: 'Revolving Hearts'},
                {icon: '💟', description: 'Heart Decoration'},
                {icon: '❣️', description: 'Heart Exclamation'},
                {icon: '💌', description: 'Love Letter'},
                {icon: '💤', description: 'Sleeping symbol'},
                {icon: '💢', description: 'Anger symbol'},
                {icon: '💣', description: 'Bomb'},
                {icon: '💥', description: 'Collision symbol'},
                {icon: '💦', description: 'Sweat Droplets'},
                {icon: '💨', description: 'Dashing Away'},
                {icon: '💫', description: 'Dizzy symbol'},
                {icon: '💬', description: 'Speech Balloon'},
                {icon: '🗨️', description: 'Empty Speech Ballon'},
                {icon: '🗯️', description: 'Right Anger Bubble'},
                {icon: '💭', description: 'Thought Balloon'},
                {icon: '🕳️', description: 'Hole'},
                {icon: '👓', description: 'Eye Glasses'},
                {icon: '🕶️', description: 'Sun Glasses'},
                {icon: '👔', description: 'Necktie'},
                {icon: '👕', description: 'Shirt'},
                {icon: '👖', description: 'Pent'},
                {icon: '🧣', description: 'Scarf'},
                {icon: '🧤', description: 'Gloves'},
                {icon: '🧥', description: 'Coat'},
                {icon: '🧦', description: 'Socks'},
                {icon: '👗', description: 'Frock'},
                {icon: '👘', description: 'Kimino'},
                {icon: '👙', description: 'Bikini'},
                {icon: '👚', description: 'Woman Clothes'},
                {icon: '👛', description: 'Purse'},
                {icon: '👜', description: 'Handbag'},
                {icon: '👝', description: 'Sack'},
                {icon: '🛍️', description: 'Shopping Bags'},
                {icon: '🎒', description: 'School bag'},
                {icon: '👞', description: 'Man\'s Shoes'},
                {icon: '👟', description: 'Athletic Shoe'},
                {icon: '👠', description: 'Heels'},
                {icon: '👡', description: 'Woman\'s Sandal'},
                {icon: '👢', description: 'Womans Boots'},
                {icon: '👑', description: 'Crown'},
                {icon: '👒', description: 'Woman\'s Hat'},
                {icon: '🎩', description: 'Top Hat'},
                {icon: '🎓', description: 'graduation cap'},
                {icon: '🧢', description: 'Baseball cap'},
                {icon: '⛑️', description: 'Rescue Worker\'s Helmet'},
                {icon: '📿', description: 'prayer beads'},
                {icon: '💄', description: 'Lipstick'},
                {icon: '💍', description: 'Ring'},
                {icon: '💎', description: 'Diamond'},

            ]
        },
        {
            title: 'Animals & Nature',
            icon: '🐶',
            data: [
                {icon: '🐸', description: 'animal'},
                {icon: '🦀', description: 'sad'},
                {icon: '🐍', description: 'sad'},
                {icon: '🐢', description: 'sad'},
                {icon: '🐠', description: 'sad'},
                {icon: '🐟', description: 'sad'},
                {icon: '🐡', description: 'sad'},
                {icon: '🐬', description: 'sad'},
                {icon: '🐳', description: 'sad'},
                {icon: '🐋', description: 'sad'},
                {icon: '🐊', description: 'sad'},
                {icon: '🐆', description: 'sad'},
                {icon: '🐅', description: 'sad'},
                {icon: '🐃', description: 'sad'},
                {icon: '🐂', description: 'sad'},
                {icon: '🐔', description: 'sad'},
                {icon: '🐶', description: 'dog animal'},
                {icon: '🐶', description: 'dog animal'},
                {icon: '🐒', description: 'dog animal'},
                {icon: '🐕', description: 'dog animal'},
                {icon: '🐩', description: 'dog animal'},
                {icon: '🐩', description: 'dog animal'},
                {icon: '🦊', description: 'wolf animal cat'},
                {icon: '🦊', description: 'wolf animal cat'},
                {icon: '🐺', description: 'wolf animal cat'},
                {icon: '🦍', description: 'monkey animal'},
                {icon: '🐵', description: 'monkey animal'},
                {icon: '🐒', description: 'cheeky facial expression monkey animal'},
                {icon: '🦍', description: 'gorrila animal'},
                {icon: '🐶', description: 'dog face animal'},
                {icon: '🐕', description: 'dog animal'},
                {icon: '🐩', description: 'poodle dog animal'},
                {icon: '🐺', description: 'wolf face animal'},
                {icon: '🦊', description: 'fox face animal'},
                {icon: '🐱', description: 'cat face animal'},
                {icon: '🐈', description: 'cat animal'},
                {icon: '🦁', description: 'lion face animal'},
                {icon: '🐯', description: 'tiger face animal'},
                {icon: '🐅', description: 'tiger animal'},
                {icon: '🐆', description: 'leopard animal'},
                {icon: '🐴', description: 'horse face animal'},
                {icon: '🐎', description: 'horse animal'},
                {icon: '🦄', description: 'unicorn face animal'},
                {icon: '🦓', description: 'zebra face animal'},
                {icon: '🦌', description: 'deer animal'},
                {icon: '🐮', description: 'cow face animal'},
                {icon: '🐂', description: 'ox animal'},
                {icon: '🐃', description: 'water buffalo animal'},
                {icon: '🐄', description: 'cow animal'},
                {icon: '🐷', description: 'pig face pig animal'},
                {icon: '🐖', description: 'animal'},
                {icon: '🐗', description: 'wild boar face animal'},
                {icon: '🐽', description: 'pig nose animal'},
                {icon: '🐏', description: 'ram animal'},
                {icon: '🐑', description: 'sheep animal'},
                {icon: '🐐', description: 'goat animal'},
                {icon: '🐪', description: 'arabian camel animal'},
                {icon: '🐫', description: 'bactrian camel animal'},
                {icon: '🦒', description: 'giraffe face animal'},
                {icon: '🐘', description: 'elephant animal'},
                {icon: '🦏', description: 'rhino animal'},
                {icon: '🐭', description: 'mouse face animal'},
                {icon: '🐁', description: 'mouse animal'},
                {icon: '🐀', description: 'rat animal'},
                {icon: '🐹', description: 'Hamster Face animal'},
                {icon: '🐰', description: 'Rabbit Face animal'},
                {icon: '🐇', description: 'rabbit animal'},
                {icon: '🐿️', description: 'red squirrel animal'},
                {icon: '🦔', description: 'Hedgehog animal'},
                {icon: '🦇', description: 'bat animal'},
                {icon: '🐻', description: 'bear face animal'},
                {icon: '🐨', description: 'koala bear face animal'},
                {icon: '🐼', description: 'panda face animal'},
                {icon: '🐾', description: 'paw prints animal'},
                {icon: '🦃', description: 'turkey animal'},
                {icon: '🐔', description: 'chicken face animal'},
                {icon: '🐓', description: 'cock animal'},
                {icon: '🐣', description: 'Hatching Chick animal'},
                {icon: '🐤', description: 'baby chick animal'},
                {icon: '🐥', description: 'Front-Facing Baby Chick animal'},
                {icon: '🐦', description: 'Bird animal'},
                {icon: '🐧', description: 'Penguin animal'},
                {icon: '🕊️', description: 'dove of peace animal'},
                {icon: '🦅', description: 'bald eagle animal'},
                {icon: '🦆', description: 'duck animal'},
                {icon: '🦉', description: 'owl animal'},
                {icon: '🐸', description: 'frog face animal'},
                {icon: '🐊', description: 'crocodiles animal'},
                {icon: '🐢', description: 'Turtles animal'},
                {icon: '🦎', description: 'lizard animal'},
                {icon: '🐍', description: 'snake animal'},
                {icon: '🐲', description: 'Dragon Face animal'},
                {icon: '🐉', description: 'dragon animal'},
                {icon: '🦕', description: 'sauropod animal'},
                {icon: '🦖', description: 'meat-eating dinosaur animal'},
                {icon: '🐳', description: 'Spouting Whale animal'},
                {icon: '🐋', description: 'Whales animal'},
                {icon: '🐬', description: 'Dolphin animal'},
                {icon: '🐟', description: 'fish animal'},
                {icon: '🐠', description: 'Tropical fish animal'},
                {icon: '🐡', description: 'Pufferfish animal'},
                {icon: '🦈', description: ' shark animal'},
                {icon: '🐙', description: 'octopus animal'},
                {icon: '🐚', description: 'Spiral Shell animal'},
                {icon: '🦀', description: 'Fresh Crab animal'},
                {icon: '🦐', description: 'shrimp animal'},
                {icon: '🦑', description: 'squid animal'},
                {icon: '🐌', description: 'snail animal'},
                {icon: '🦋', description: 'butterfly animal'},
                {icon: '🐛', description: 'Insects animal'},
                {icon: '🐜', description: 'ant animal'},
                {icon: '🐝', description: ' honey bee animal'},
                {icon: '🐞', description: 'Lady Beetle animal'},
                {icon: '🦗', description: 'cricket animal'},
                {icon: '🕷️', description: 'Spider animal'},
                {icon: '🕸️', description: 'spider web animal'},
                {icon: '🦂', description: 'Scorpions animal'},
                {icon: '💐', description: 'flower bouquet plants'},
                {icon: '🌸', description: 'cherry blossom plants'},
                {icon: '💮', description: ' white flower plants'},
                {icon: '🏵️', description: ' rosette plants'},
                {icon: '🌹', description: 'rose flower plants'},
                {icon: '🥀', description: 'Wilted Flower plants'},
                {icon: '🌺', description: 'Hibiscus flower plants'},
                {icon: '🌻', description: 'sunflower flower plants'},
                {icon: '🌼', description: 'Blossom flower'},
                {icon: '🌷', description: 'Tulips flower'},
                {icon: '🌱', description: 'seedling flower'},
                {icon: '🌲', description: 'evergreen tree'},
                {icon: '🌳', description: 'deciduous tree'},
                {icon: '🌴', description: 'palm tree tree'},
                {icon: '🌵', description: 'cactus plants'},
                {icon: '🌾', description: 'rice plant plants'},
                {icon: '🌿', description: 'Herb plants'},
                {icon: '☘️', description: 'Shamrock plants'},
                {icon: '🍀', description: 'four-leaf clover plants'},
                {icon: '🍁', description: 'maple leaf plants'},
                {icon: '🍂', description: 'Fallen Leaf plants'},
                {icon: '🍃', description: 'Leaf Fluttering in Wind animal plants'},
            ]
        },
        {
            title: 'Food & Drink',
            icon: '🍎',
            data: [
                {icon: '🍇', description: 'grapes fruit food'},
                {icon: '🍞', description: 'fruit food'},
                {icon: '🍔', description: 'fruit food'},
                {icon: '🍟', description: 'fruit food'},
                {icon: '🧀', description: 'fruit food'},
                {icon: '🍗', description: 'fruit food'},
                {icon: '🍖', description: 'fruit food'},
                {icon: '🌭', description: 'fruit food'},
                {icon: '🍕', description: 'fruit food'},
                {icon: '🍈', description: 'food'},
                {icon: '🍉', description: 'food fruit '},
                {icon: '🍊', description: ' food fruit '},
                {icon: '🍋', description: ' food fruit '},
                {icon: '🍌', description: 'banana food fruit '},
                {icon: '🍍', description: 'food fruit '},
                {icon: '🍎', description: 'apple food fruit'},
                {icon: '🍎', description: 'food fruit'},
                {icon: '🍐', description: 'food fruit'},
                {icon: '🍒', description: 'cherry food fruit'},
                {icon: '🍓', description: 'rasberry food fruit'},
                {icon: '🥝', description: 'kiwi food fruit'},
                {icon: '🍅', description: 'tomato food fruit'},
                {icon: '🥥', description: 'coconut food fruit'},
                {icon: '🥑', description: 'avocado food fruit'},
                {icon: '🍆', description: 'turnip food fruit'},
                {icon: '🥔', description: 'potato food fruit'},
                {icon: '🥕', description: 'carrot food fruit'},
                {icon: '🌽', description: 'corn food fruit'},
                {icon: '🌶️', description: 'red chilli food fruit'},
                {icon: '🥒', description: 'peas food fruit'},
                {icon: '🥦', description: 'broccoli food fruit'},
                {icon: '🍄', description: 'mushroom food fruit'},
                {icon: '🥜', description: 'food fruit'},
                {icon: '🌰', description: 'food fruit'},
                {icon: '🍞', description: 'food fruit'},
                {icon: '🥐', description: 'fried shrimp food fruit'},
                {icon: '🥖', description: 'food fruit'},
                {icon: '🥨', description: 'food fruit'},
                {icon: '🥞', description: 'food fruit'},
                {icon: '🧀', description: 'cheese food fruit'},
                {icon: '🍖', description: 'Meat food fruit'},
                {icon: '🍗', description: 'poultry leg food fruit'},
                {icon: '🥩', description: 'food fruit'},
                {icon: '🥓', description: 'candy food fruit'},
                {icon: '🍔', description: 'burger food fruit'},
                {icon: '🍟', description: 'french fries food fruit'},
                {icon: '🍕', description: 'pizza food fruit'},
                {icon: '🌭', description: 'hot dog food fruit'},
                {icon: '🥪', description: 'sandwich food fruit'},
                {icon: '🌮', description: 'Taco food fruit'},
                {icon: '🌯', description: 'Burrito food fruit'},
                {icon: '🥙', description: 'food fruit'},
                {icon: '🥚', description: 'egg food fruit'},
                {icon: '🍳', description: 'cooking food fruit'},
                {icon: '🥘', description: 'food fruit'},
                {icon: '🍲', description: 'food fruit'},
                {icon: '🥣', description: 'food fruit'},
                {icon: '🥗', description: 'food fruit'},
                {icon: '🍿', description: 'popcorn food fruit'},
                {icon: '🥫', description: 'food fruit'},
                {icon: '🍱', description: 'bento box food fruit'},
                {icon: '🍘', description: 'cooked rice food fruit'},
                {icon: '🍙', description: 'rice ball food fruit'},
                {icon: '🍚', description: 'food fruit'},
                {icon: '🍛', description: 'post of food food fruit'},
                {icon: '🍜', description: 'Maggi food fruit'},
                {icon: '🍝', description: 'spaghetti food fruit'},
                {icon: '🍠', description: 'food fruit'},
                {icon: '🍢', description: 'Oden food fruit'},
                {icon: '🍣', description: 'sushi food fruit'},
                {icon: '🍤', description: 'food fruit'},
                {icon: '🍥', description: 'fish cake food fruit'},
                {icon: '🍡', description: 'food fruit'},
                {icon: '🥟', description: 'food fruit'},
                {icon: '🥠', description: 'food fruit'},
                {icon: '🥡', description: 'food fruit'},
                {icon: '🍦', description: 'soft ice cream food fruit'},
                {icon: '🍧', description: 'shaved ice food fruit'},
                {icon: '🍨', description: 'ice cream food fruit'},
                {icon: '🍩', description: 'doughut food fruit'},
                {icon: '🍪', description: 'cookies food fruit'},
                {icon: '🎂', description: 'cake food fruit'},
                {icon: '🍰', description: 'shortcake food fruit'},
                {icon: '🥧', description: 'food fruit'},
                {icon: '🍫', description: 'chocolate food fruit'},
                {icon: '🍬', description: 'candy food fruit'},
                {icon: '🍭', description: 'lollypop food fruit'},
                {icon: '🍮', description: 'food fruit'},
                {icon: '🍯', description: 'coconut  water food fruit'},
                {icon: '🍼', description: 'milk food fruit'},
                {icon: '🥛', description: 'water food fruit'},
                {icon: '☕', description: 'tea food fruit'},
                {icon: '🍵', description: 'coffee food fruit'},
                {icon: '🍶', description: 'sake bottle and cup food fruit'},
                {icon: '🍾', description: 'Bottle with popping cork food fruit'},
                {icon: '🍷', description: 'Wine glass food fruit'},
                {icon: '🍸', description: 'glass cocktail glass food fruit'},
                {icon: '🍹', description: 'glass tropical drink food fruit'},
                {icon: '🍺', description: 'glass beer mug food fruit'},
                {icon: '🍻', description: 'glass food fruit'},
                {icon: '🥂', description: 'food fruit'},
                {icon: '🥃', description: 'food fruit'},
                {icon: '🥤', description: 'food fruit'},
                {icon: '🥢', description: 'food fruit'},
                {icon: '🍽️', description: 'fork and knife with plate food fruit'},
                {icon: '🍴', description: 'fork and knife food fruit'},
                {icon: '🥄', description: 'spoon food fruit'},
                {icon: '🔪', description: 'knife food fruit'},
                {icon: '🏺', description: 'food fruit'},
            ]
        },
        {
            title: 'Activity',
            icon: '⚽',
            data: [
                {icon: '🎃', description: 'halloween enjoy activity'},
                {icon: '🎄', description: 'tree enjoy activity'},
                {icon: '🎆', description: 'shine enjoy activity'},
                {icon: '🎇', description: 'shine enjoy activity'},
                {icon: '✨', description: 'star sky activity'},
                {icon: '🎈', description: 'balloon enjoy celebrate activity'},
                {icon: '🎉', description: 'enjoy celebrate birthday activity'},
                {icon: '🎊', description: 'activity'},
                {icon: '🎋', description: 'activity'},
                {icon: '🎍', description: 'activity'},
                {icon: '🎎', description: 'activity'},
                {icon: '🎏', description: 'activity'},
                {icon: '🎐', description: 'activity'},
                {icon: '🎑', description: 'activity'},
                {icon: '🎀', description: 'flower activity'},
                {icon: '🎁', description: 'gift box activity'},
                {icon: '🎗️', description: 'ribon activity'},
                {icon: '🎟️', description: 'chip activity'},
                {icon: '🎫', description: 'chip activity'},
                {icon: '🎖️', description: 'medal activity'},
                {icon: '🏆', description: 'medal activity'},
                {icon: '🏅', description: 'medal activity'},
                {icon: '🥇', description: 'medal activity'},
                {icon: '🥈', description: 'medal activity'},
                {icon: '🥉', description: 'medal activity'},
                {icon: '⚽', description: 'football activity'},
                {icon: '⚾', description: 'football activity'},
                {icon: '🏀', description: 'football activity'},
                {icon: '🏐', description: 'bascketball activity'},
                {icon: '🏈', description: 'bascketball  activity'},
                {icon: '🏉', description: 'bascketball activity'},
                {icon: '🎾', description: 'badmainten activity'},
                {icon: '🎱', description: 'ball activity'},
                {icon: '🎳', description: 'play activity'},
                {icon: '🏏', description: 'bat ball cricket activity'},
                {icon: '🏑', description: 'hockey activity'},
                {icon: '🏒', description: 'hockey activity'},
                {icon: '🏓', description: 'play activity'},
                {icon: '🏸', description: 'badmainten activity'},
                {icon: '🥊', description: 'activity'},
                {icon: '🥋', description: 'dress shirt activity'},
                {icon: '🥅', description: 'activity'},
                {icon: '🎯', description: 'play activity'},
                {icon: '⛳', description: 'play flag activity'},
                {icon: '⛸️', description: 'shoes riding activity'},
                {icon: '🎣', description: 'activity'},
                {icon: '🎽', description: 'shirt activity'},
                {icon: '🎿', description: 'toy activity'},
                {icon: '🛷', description: 'activity'},
                {icon: '🥌', description: 'toy activity'},
                {icon: '🎮', description: 'toy activity'},
                {icon: '🕹️', description: 'toy activity'},
                {icon: '🕹', description: 'activity'},
                {icon: '🎲', description: 'dice activity'},
                {icon: '♠', description: 'cards activity'},
                {icon: '♥', description: 'cards activity'},
                {icon: '♦', description: 'cards activity'},
                {icon: '♣', description: 'cards activity'},
                {icon: '🃏', description: 'activity'},
                {icon: '🀄', description: 'activity'},
                {icon: '🎴', description: 'activity'},

            ]
        },
        {
            title: 'Travel & Places',
            icon: '🚗',
            data: [
                {icon: '🌍', description: 'earth Travel & Places'},
                {icon: '🌐', description: 'Travel earth colorfull & Places'},
                {icon: '🗺️', description: 'Travel & Places'},
                {icon: '🗾', description: 'Travel & Places'},
                {icon: '🏔️', description: 'Travel & Places ice mountain glashier'},
                {icon: '🌋', description: 'Travel & Places mountain'},
                {icon: '🗻', description: 'Travel & Places mountain'},
                {icon: '🏕️', description: 'Travel & Places home'},
                {icon: '🏖️', description: 'Travel & Places umbrella'},
                {icon: '🏜️', description: 'Travel & Places nature'},
                {icon: '🏝️', description: 'Travel & Places tree nature'},
                {icon: '🏞️', description: 'Travel & Places nature snow'},
                {icon: '🏟️', description: 'Travel & Places home town'},
                {icon: '🏛️', description: 'Travel & Places home town'},
                {icon: '🏗️', description: 'Travel & Places'},
                {icon: '🏘️', description: 'Travel & Places home'},
                {icon: '🏙️', description: 'Travel & Places bildings city'},
                {icon: '🏚️', description: 'Travel & Places home bilding'},
                {icon: '🏠', description: 'Travel & Places home bilding'},
                {icon: '🏡', description: 'Travel & Places home bilding'},
                {icon: '🏢', description: 'Travel & Places home bilding'},
                {icon: '🏣', description: 'Travel & Places home bilding'},
                {icon: '🏤', description: 'Travel & Places home bilding'},
                {icon: '🏥', description: 'Travel & Places home bilding'},
                {icon: '🏦', description: 'Travel & Places home bilding'},
                {icon: '🏨', description: 'Travel & Places home bilding'},
                {icon: '🏩', description: 'Travel & Places home bilding'},
                {icon: '🏪', description: 'Travel & Places home bilding'},
                {icon: '🏫', description: 'Travel & Places home bilding'},
                {icon: '🏬', description: 'Travel & Places home bilding'},
                {icon: '🏭', description: 'Travel & Places home bilding'},
                {icon: '🏯', description: 'Travel & Places home bilding'},
                {icon: '🏰', description: 'Travel & Places home bilding'},
                {icon: '💒', description: 'Travel & Places home bilding'},
                {icon: '🗼', description: 'Travel & Places home bilding'},
                {icon: '🗽', description: 'Travel & Places home bilding'},
                {icon: '⛪', description: 'Travel & Places home bilding'},
                {icon: '🕌', description: 'Travel & Places home bilding'},
                {icon: '🕍', description: 'Travel & Places home bilding'},
                {icon: '⛩', description: 'Travel & Places home bilding'},
                {icon: '️🕋', description: 'Travel & Places home allah'},
                {icon: '⛲', description: 'Travel & Places show'},
                {icon: '⛺', description: 'Travel & Places home bilding'},
                {icon: '🌁', description: 'Travel & Places home bilding city'},
                {icon: '🌃', description: 'Travel & Places home bilding city'},
                {icon: '🌄', description: 'Travel & Places'},
                {icon: '🌅', description: 'Travel & Places'},
                {icon: '🌆', description: 'Travel & Places'},
                {icon: '🌇', description: 'Travel & Places'},
                {icon: '🌉', description: 'Travel & Places'},
                {icon: '♨️', description: 'travel show toy'},
                {icon: '🌌', description: 'travel ring colorfull toy'},
                {icon: '🎠', description: 'travel horse toy'},
                {icon: '🎡', description: 'travel toy game arraow'},
                {icon: '🎢', description: 'travel bridge'},
                {icon: '💈', description: 'travel'},
                {icon: '🎪', description: 'travel camp home'},
                {icon: '🎭', description: 'travel joker faces'},
                {icon: '🖼️', description: 'travel picture'},
                {icon: '🎨', description: 'travel colors'},
                {icon: '🎰', description: 'travel numbers 777'},
                {icon: '🚂', description: 'travel train'},
                {icon: '🚃', description: 'travel train'},
                {icon: '🚄', description: 'travel train'},
                {icon: '🚅', description: 'travel train'},
                {icon: '🚆', description: 'travel train'},
                {icon: '🚇', description: 'travel train'},
                {icon: '🚈', description: 'travel train'},
                {icon: '🚉', description: 'travel train'},
                {icon: '🚊', description: 'travel train'},
                {icon: '🚝', description: 'travel train'},
                {icon: '🚞', description: 'travel home'},
                {icon: '🚋', description: 'travel home'},
                {icon: '🚌', description: 'travel bus'},
                {icon: '🚍', description: 'travel bus'},
                {icon: '🚎', description: 'travel bus'},
                {icon: '🚐', description: 'travel van'},
                {icon: '🚑', description: 'travel ambulance emergency'},
                {icon: '🚒', description: 'travel emergency fire brigade'},
                {icon: '🚓', description: 'travel police car'},
                {icon: '🚔', description: 'travel police car'},
                {icon: '🚕', description: 'travel taxi car'},
                {icon: '🚖', description: 'travel caar'},
                {icon: '🚗', description: 'travel car red'},
                {icon: '🚘', description: 'travel car jeep '},
                {icon: '🚙', description: 'travel jeep'},
                {icon: '🚚', description: 'travel van truck'},
                {icon: '🚛', description: 'travel truck'},
                {icon: '🚜', description: 'travel trackter agriculture'},
                {icon: '🚲', description: 'travel cycle'},
                {icon: '🛴', description: 'travel cycle'},
                {icon: '🛵', description: 'travel bike'},
                {icon: '🚏', description: 'travel'},
                {icon: '🛣️', description: 'travel'},
                {icon: '🛤️', description: 'travel nature'},
                {icon: '⛽', description: 'travel phone'},
                {icon: '🚨', description: 'travel'},
                {icon: '🚥', description: 'travel signal'},
                {icon: '🚦', description: 'travel signal'},
                {icon: '🚧', description: 'travel block'},
                {icon: '🛑', description: 'travel'},
                {icon: '⚓', description: 'travel'},
                {icon: '⛵', description: 'travel'},
                {icon: '🛶', description: 'travel color toy brush'},
                {icon: '🚤', description: 'travel ship water'},
                {icon: '🛳️', description: 'travel ship'},
                {icon: '⛴️', description: 'travel ship'},
                {icon: '🛥️', description: 'travel ship'},
                {icon: '🚢', description: 'travel ship'},
                {icon: '✈️', description: 'travel aeroplane'},
                {icon: '🛩️', description: 'travel aeroplane'},
                {icon: '🛫', description: 'travel aeroplane'},
                {icon: '🛬', description: 'travel aeroplane'},
                {icon: '💺', description: 'travel chair'},
                {icon: '🚁', description: 'travel helicopter'},
                {icon: '🚟', description: 'travel chair lift'},
                {icon: '🚡', description: 'travel chair lift'},
                {icon: '🛰️', description: 'travel plane'},
                {icon: '🚀', description: 'travel rocket'},
                {icon: '🛸', description: 'travel alien ship'},
                {icon: '🛎️', description: 'travel'},
                {icon: '🚪', description: 'travel'},
                {icon: '🛏️', description: 'travel bed'},
                {icon: '🛏', description: 'travel'},
                {icon: '🛋️', description: 'travel'},
                {icon: '🚽', description: 'travel'},
                {icon: '🚿', description: 'travel'},
                {icon: '🛁', description: 'travel'},
                {icon: '⌛', description: 'travel'},
                {icon: '⏳', description: 'travel'},
                {icon: '⌚', description: 'travel watch time'},
                {icon: '⏰', description: 'travel watch time'},
                {icon: '⏱️', description: 'travel watch time'},
                {icon: '⏲️', description: 'travel watch time'},
                {icon: '🕰️', description: 'travel watch time'},
                {icon: '🕛', description: 'travel watch time'},
                {icon: '🕧', description: 'travel watch time'},
                {icon: '🕐', description: 'travel watch time'},
                {icon: '🕜', description: 'travel watch time'},
                {icon: '🕑', description: 'travel watch time'},
                {icon: '🕝', description: 'travel watch time'},
                {icon: '🕒', description: 'travel watch time'},
                {icon: '🕞', description: 'travel watch time'},
                {icon: '🕓', description: 'travel watch time'},
                {icon: '🕟', description: 'travel watch time'},
                {icon: '🕔', description: 'travel watch time'},
                {icon: '🕠', description: 'travel watch time'},
                {icon: '🕕', description: 'travel watch time'},
                {icon: '🕖', description: 'travel watch time'},
                {icon: '🕢', description: 'travel watch time'},
                {icon: '🕗', description: 'travel watch time'},
                {icon: '🕣', description: 'travel watch time'},
                {icon: '🕘', description: 'travel watch time'},
                {icon: '🕤', description: 'travel watch time'},
                {icon: '🕙', description: 'travel watch time'},
                {icon: '🕥', description: 'travel watch time'},
                {icon: '🕚', description: 'travel watch time'},
                {icon: '🕦', description: 'travel watch time'},
                {icon: '🌑', description: 'travel moon'},
                {icon: '🌒', description: 'travel moon'},
                {icon: '🌓', description: 'travel moon'},
                {icon: '🌔', description: 'travel moon'},
                {icon: '🌕', description: 'travel full moon'},
                {icon: '🌖', description: 'travel moon'},
                {icon: '🌗', description: 'travel moon'},
                {icon: '🌘', description: 'travel moon'},
                {icon: '🌙', description: 'travel moon'},
                {icon: '🌚', description: 'travel moon'},
                {icon: '🌛', description: 'travel moon'},
                {icon: '🌜', description: 'travel moon'},
                {icon: '🌡️', description: 'travel heat'},
                {icon: '☀️', description: 'travel sunlight'},
                {icon: '🌝', description: 'travel sun'},
                {icon: '🌞', description: 'travel sun smile'},
                {icon: '⭐', description: 'travel star'},
                {icon: '🌟', description: 'travel start'},
                {icon: '🌠', description: 'travel'},
                {icon: '☁', description: 'travel cloud'},
                {icon: '️⛅', description: 'travel morining cloud'},
                {icon: '⛈️', description: 'travel cloud'},
                {icon: '🌤️', description: 'travel sunligh cloudt'},
                {icon: '🌥️', description: 'travel sunlight cloud'},
                {icon: '🌦️', description: 'travel sunlight raining cloud'},
                {icon: '🌧️', description: 'travel raining cloud'},
                {icon: '🌨️', description: 'travel raining cloud'},
                {icon: '🌩️', description: 'travel cloud'},
                {icon: '🌪️', description: 'travel'},
                {icon: '🌫️', description: 'travel'},
                {icon: '🌬️', description: 'travel women girl face'},
                {icon: '🌀', description: 'travel toy'},
                {icon: '🌈', description: 'travel rainbow colors colorfull'},
                {icon: '🌂', description: 'travel umbrella'},
                {icon: '☂️', description: 'travel umbrella'},
                {icon: '☔', description: 'umbrella travel'},
                {icon: '⛱️', description: 'umbrella travel'},
                {icon: '⚡', description: 'travel energy level'},
                {icon: '❄️', description: 'travel toy'},
                {icon: '☃️', description: 'travel snow toy'},
                {icon: '⛄', description: 'travel snow toy'},
                {icon: '☄️', description: 'travel'},
                {icon: '🔥', description: 'travel heat fire'},
                {icon: '💧', description: 'travel water drop'},
                {icon: '🌊', description: 'travel water'},
            ]
        },
        {
            title: 'Objects',
            icon: '💡',
            data: [
                {icon: '🔇', description: 'speaker mute enjoy objects'},
                {icon: '🔈', description: 'speaker mute enjoy objects'},
                {icon: '🔉', description: 'speaker loud enjoy objects'},
                {icon: '🔊', description: 'speaker loud enjoy objects'},
                {icon: '📢', description: 'speaker loud enjoy objects'},
                {icon: '📣', description: 'speaker loud enjoy objects'},
                {icon: '📯', description: 'piano song mute enjoy objects'},
                {icon: '🔔', description: 'objects bell'},
                {icon: '☂', description: `objects umbrella`},
                {icon: '☔', description: 'objects umbrella'},
                {icon: '🔕', description: 'objects bell block no sound'},
                {icon: '🎼', description: 'Objects'},
                {icon: '🎵', description: 'Objects music'},
                {icon: '🎶', description: 'Objects music'},
                {icon: '🎙️', description: 'Objects speaker mike'},
                {icon: '🎚', description: 'Objects'},
                {icon: '️🎛️', description: 'Objects dice'},
                {icon: '🎤', description: 'Objects speaker'},
                {icon: '🎧', description: 'Objects headphone'},
                {icon: '📻', description: 'Objects radio'},
                {icon: '🎷', description: 'Objects music'},
                {icon: '🎸', description: 'Objects gator'},
                {icon: '🎹', description: 'Objects piano'},
                {icon: '🎺', description: 'Objects music'},
                {icon: '🎻', description: 'Objects gator'},
                {icon: '🥁', description: 'Objects drum'},
                {icon: '📱', description: 'Objects'},
                {icon: '📲', description: 'Objects'},
                {icon: '☎', description: 'Objects phone'},
                {icon: '📞', description: 'Objects phone'},
                {icon: '📟', description: 'Objects'},
                {icon: '📠', description: 'Objects phone'},
                {icon: '🔋', description: 'Objects battery level energy'},
                {icon: '🔌', description: 'Objects cable switch'},
                {icon: '💻', description: 'Objects laptop computer'},
                {icon: '🖥️', description: 'Objects lcd led screen'},
                {icon: '🖨️', description: 'Objects printer'},
                {icon: '⌨️', description: 'Objects'},
                {icon: '🖱️', description: 'Objects mouse'},
                {icon: '🖲️', description: 'Objects mouse'},
                {icon: '💽', description: 'Objects disc movie'},
                {icon: '💾', description: 'Objects floppy disk'},
                {icon: '💿', description: 'Objects disk'},
                {icon: '📀', description: 'Objects golden desk'},
                {icon: '🎥', description: 'Objects movie'},
                {icon: '🎞️', description: 'Objects'},
                {icon: '📽', description: 'Objects'},
                {icon: '🎬', description: 'Objects movie'},
                {icon: '📺', description: 'Objects tv'},
                {icon: '📷', description: 'Objects camera'},
                {icon: '📸', description: 'Objects camera'},
                {icon: '📹', description: 'Objects'},
                {icon: '📼', description: 'Objects'},
                {icon: '🔍', description: 'Objects search'},
                {icon: '🔎', description: 'Objects search'},
                {icon: '🔬', description: 'Objects'},
                {icon: '🔭', description: 'Objects'},
                {icon: '📡', description: 'Objects antenna'},
                {icon: '🕯️', description: 'Objects'},
                {icon: '🕯', description: 'Objects'},
                {icon: '🔦', description: 'Objects'},
                {icon: '🏮', description: 'Objects'},
                {icon: '📔', description: 'Objects book'},
                {icon: '📕', description: 'Objects book'},
                {icon: '📖', description: 'Objects book'},
                {icon: '📗', description: 'Objects book'},
                {icon: '📘', description: 'Objects book'},
                {icon: '📙', description: 'Objects book'},
                {icon: '📚', description: 'Objects'},
                {icon: '📓', description: 'Objects book'},
                {icon: '📒', description: 'Objects book'},
                {icon: '📃', description: 'Objects paper'},
                {icon: '📜', description: 'Objects paper'},
                {icon: '📄', description: 'Objects paper'},
                {icon: '📰', description: 'Objects paper'},
                {icon: '🗞️', description: 'Objects'},
                {icon: '📑', description: 'Objects'},
                {icon: '🔖', description: 'Objects'},
                {icon: '🏷️', description: 'Objects'},
                {icon: '💰', description: 'Objects money dollar'},
                {icon: '💴', description: 'Objects'},
                {icon: '💵', description: 'Objects'},
                {icon: '💶', description: 'Objects'},
                {icon: '💷', description: 'Objects'},
                {icon: '💸', description: 'Objects'},
                {icon: '💳', description: 'Objects'},
                {icon: '💹', description: 'Objects'},
                {icon: '💱', description: 'Objects'},
                {icon: '💲', description: 'Objects dollar'},
                {icon: '✉', description: 'Objects mail message'},
                {icon: '📧', description: 'Objects mail'},
                {icon: '📨', description: 'Objects mail message'},
                {icon: '📩', description: 'Objects message'},
                {icon: '📤', description: 'Objects'},
                {icon: '📥', description: 'Objects'},
                {icon: '📦', description: 'Objects'},
                {icon: '📫', description: 'Objects'},
                {icon: '📪', description: 'Objects mailbox'},
                {icon: '📬', description: 'Objects mailbox'},
                {icon: '📭', description: 'Objects mailbox'},
                {icon: '📮', description: 'Objects mailbox'},
                {icon: '🗳️', description: 'Objects'},
                {icon: '✏️', description: 'Objects pencil'},
                {icon: '✒️', description: 'Objects pen'},
                {icon: '🖋️', description: 'Objects pen'},
                {icon: '🖍️', description: 'Objects pen'},
                {icon: '📝', description: 'Objects text paper'},
                {icon: '💼', description: 'Objects bag briefcase'},
                {icon: '📁', description: 'Objects folder'},
                {icon: '📂', description: 'Objects open folder'},
                {icon: '🗂️', description: 'Objects box'},
                {icon: '📅', description: 'Objects calender'},
                {icon: '📆', description: 'Objects calender 31'},
                {icon: '🗒️', description: 'Objects'},
                {icon: '🗓️', description: 'Objects calender'},
                {icon: '📇', description: 'Objects'},
                {icon: '📈', description: 'Objects graph'},
                {icon: '📉', description: 'Objects graph'},
                {icon: '📊', description: 'Objects graph'},
                {icon: '📋', description: 'Objects paper'},
                {icon: '📌', description: 'Objects pin'},
                {icon: '📍', description: 'Objects joystick'},
                {icon: '📎', description: 'Objects pin'},
                {icon: '🖇️', description: 'Objects'},
                {icon: '📏', description: 'Objects geometry foot'},
                {icon: '📐', description: 'Objects geometry'},
                {icon: '✂️', description: 'Objects scissor'},
                {icon: '🗃️', description: 'Objects'},
                {icon: '🗄️', description: 'Objects'},
                {icon: '🗑️', description: 'Objects trash basket'},
                {icon: '🔒', description: 'Objects lock'},
                {icon: '🔓', description: 'Objects lock'},
                {icon: '🔏', description: 'Objects lock'},
                {icon: '🔐', description: 'Objects lock'},
                {icon: '🔑', description: 'Objects key'},
                {icon: '🗝️', description: 'Objects key'},
                {icon: '🔨', description: 'Objects haber'},
                {icon: '⛏️', description: 'Objects hammer'},
                {icon: '⚒️', description: 'Objects axe'},
                {icon: '🛠️', description: 'Objects equipments'},
                {icon: '🗡️', description: 'Objects war'},
                {icon: '⚔️', description: 'Objects war'},
                {icon: '🔫', description: 'Objects watergun'},
                {icon: '🏹', description: 'Objects arrow'},
                {icon: '🛡️', description: 'Objects defend'},
                {icon: '🔧', description: 'Objects'},
                {icon: '🔩', description: 'Objects'},
                {icon: '⚙️', description: 'Objects setting'},
                {icon: '🗜️', description: 'Objects'},
                {icon: '⚗️', description: 'Objects'},
                {icon: '⚖️', description: 'Objects balance'},
                {icon: '🔗', description: 'Objects'},
                {icon: '⛓️', description: 'Objects'},
                {icon: '💉', description: 'Objects injection'},
                {icon: '💊', description: 'Objects capsule'},
                {icon: '🚬', description: 'Objects smoke'},
                {icon: '⚰', description: 'Objects'},
                {icon: '️⚱', description: 'Objects'},
                {icon: '🗿', description: 'Objects'},
                {icon: '🛢️', description: 'Objects coins'},
                {icon: '🔮', description: 'Objects'},
                {icon: '🛒', description: 'Objects carry'},
            ]
        },
        {
            title: 'Symbols',
            icon: '🔻',
            data: [
                {icon: '🏧', description: 'symbols'},
                {icon: '🚮', description: 'man symbols'},
                {icon: '🚰', description: 'water symbols'},
                {icon: '♿', description: 'wheelchair symbols'},
                {icon: '🚹', description: 'man person symbols'},
                {icon: '🚺', description: 'women symbols'},
                {icon: '🚻', description: 'couple symbols'},
                {icon: '🚼', description: 'symbols'},
                {icon: '🚾', description: 'wc symbols'},
                {icon: '🛂', description: 'man symbols'},
                {icon: '🛃', description: 'man symbols'},
                {icon: '🛄', description: 'symbols'},
                {icon: '🛅', description: 'symbols'},
                {icon: '⚠', description: 'danger symbols'},
                {icon: '🚸', description: 'symbols'},
                {icon: '⛔', description: 'minus decrease symbols'},
                {icon: '🚫', description: 'symbols block'},
                {icon: '🚳', description: 'symbols drive bicycle block'},
                {icon: '🚭', description: 'symbols'},
                {icon: '🚯', description: 'symbols'},
                {icon: '🚱', description: 'symbols water block'},
                {icon: '🚷', description: 'symbols block'},
                {icon: '📵', description: 'symbols block not allowed'},
                {icon: '🔞', description: 'symbols under eighteen  block not allowed'},
                {icon: '☢', description: 'symbols  danger'},
                {icon: '☣', description: 'symbols'},
                {icon: '⬆', description: 'symbols arrow up'},
                {icon: '↗', description: 'symbols arrow'},
                {icon: '➡', description: 'symbols arrow right'},
                {icon: '↘', description: 'symbols arrow'},
                {icon: '⬇', description: 'symbols arrow down'},
                {icon: '↙', description: 'symbols arrow'},
                {icon: '⬅', description: 'symbols left'},
                {icon: '↖', description: 'symbols arrow'},
                {icon: '↕', description: 'symbols arrow'},
                {icon: '↔', description: 'symbols arrow'},
                {icon: '↩', description: 'symbols arrow'},
                {icon: '↪', description: 'symbols arrow right'},
                {icon: '⤴', description: 'symbols arrow upward'},
                {icon: '⤵', description: 'symbols arrow downward'},
                {icon: '🔃', description: 'symbols arrow'},
                {icon: '🔄', description: 'symbols circle spin arrow'},
                {icon: '🔙', description: 'symbols arrow back'},
                {icon: '🔚', description: 'symbols arrow back end'},
                {icon: '🔛', description: 'symbols arrow on'},
                {icon: '🔜', description: 'symbols arrow soon'},
                {icon: '🔝', description: 'symbols arrow top'},
                {icon: '🛐', description: 'symbols'},
                {icon: '⚛️', description: 'symbols'},
                {icon: '🕉️', description: 'symbols'},
                {icon: '✡', description: 'symbols'},
                {icon: '☸', description: 'symbols'},
                {icon: '☯', description: 'symbols'},
                {icon: '✝', description: 'symbols sign'},
                {icon: '☦', description: 'symbols'},
                {icon: '☪', description: 'symbols moon'},
                {icon: '☮', description: 'symbols'},
                {icon: '🕎', description: 'symbols'},
                {icon: '🔯', description: 'symbols'},
                {icon: '♈', description: 'symbols'},
                {icon: '♉', description: 'symbols'},
                {icon: '♊', description: 'symbols'},
                {icon: '♋', description: 'symbols'},
                {icon: '♌', description: 'symbols'},
                {icon: '♍', description: 'symbols'},
                {icon: '♎', description: 'symbols'},
                {icon: '♏', description: 'symbols'},
                {icon: '♐', description: 'symbols'},
                {icon: '♑', description: 'symbols'},
                {icon: '♒', description: 'symbols'},
                {icon: '♓', description: 'symbols'},
                {icon: '⛎', description: 'symbols'},
                {icon: '🔀', description: 'symbols share cross'},
                {icon: '🔀', description: 'symbols cross'},
                {icon: '🔁', description: 'symbols spin'},
                {icon: '🔂', description: 'symbols'},
                {icon: '▶', description: 'symbols play'},
                {icon: '⏩', description: 'symbols forward'},
                {icon: '⏭', description: 'symbols stop'},
                {icon: '⏯', description: 'symbols stop'},
                {icon: '◀', description: 'symbols backward'},
                {icon: '⏪', description: 'symbols backward'},
                {icon: '⏮', description: 'symbols previous'},
                {icon: '🔼', description: 'symbols up'},
                {icon: '⏫', description: 'symbols up'},
                {icon: '🔽', description: 'symbols downward'},
                {icon: '⏬', description: 'symbols downward'},
                {icon: '⏸', description: 'symbols stop'},
                {icon: '⏹', description: 'symbols stop'},
                {icon: '⏺', description: 'symbols'},
                {icon: '⏏', description: 'symbols'},
                {icon: '🎦', description: 'symbols'},
                {icon: '🔅', description: 'symbols'},
                {icon: '🔆', description: 'symbols'},
                {icon: '📶', description: 'symbols'},
                {icon: '📳', description: 'symbols'},
                {icon: '📴', description: 'symbols off'},
                {icon: '♀', description: 'symbols single individual'},
                {icon: '♂', description: 'symbols'},
                {icon: '⚕', description: 'symbols'},
                {icon: '♻', description: 'symbols'},
                {icon: '⚜', description: 'symbols'},
                {icon: '📛', description: 'symbols'},
                {icon: '🔰', description: 'symbols'},
                {icon: '⭕', description: 'symbols'},
                {icon: '✅', description: 'symbols tick true'},
                {icon: '☑', description: 'symbols true'},
                {icon: '✔', description: 'symbols true'},
                {icon: '✖', description: 'symbols cross'},
                {icon: '❌', description: 'symbols cross'},
                {icon: '❎', description: 'symbols cross'},
                {icon: '➕', description: 'symbols plus'},
                {icon: '➖', description: 'symbols minus'},
                {icon: '➗', description: 'symbols divide'},
                {icon: '➰', description: 'symbols'},
                {icon: '➿', description: 'symbols'},
                {icon: '〽', description: 'symbols'},
                {icon: '✳', description: 'symbols'},
                {icon: '✴', description: 'symbols'},
                {icon: '❓', description: 'symbols ? question mark'},
                {icon: '❔', description: 'symbols? question mark'},
                {icon: '❕', description: 'symbols'},
                {icon: '〰', description: 'symbols'},
                {icon: '©', description: 'symbols c copy'},
                {icon: '®', description: 'symbols'},
                {icon: '™', description: 'symbols'},
                {icon: '🔟', description: 'symbols 10 ten'},
                {icon: '💯', description: 'symbols 100 hundred perfect'},
                {icon: '🔠', description: 'symbols abcd alphabets capital'},
                {icon: '🔡', description: 'symbols abcd alphabets small'},
                {icon: '🔢', description: 'symbols number 1234'},
                {icon: '🔣', description: 'symbols'},
                {icon: '🔤', description: 'symbols'},
                {icon: '🅰️', description: 'symbols a'},
                {icon: '🆎', description: 'symbols ab'},
                {icon: '🅱️', description: 'symbols b'},
                {icon: '🆑', description: 'symbols cl'},
                {icon: '🆒', description: 'symbols cool'},
                {icon: '🆓', description: 'symbols free'},
                {icon: 'ℹ', description: 'symbols i info'},
                {icon: '🆔', description: 'symbols id'},
                {icon: 'Ⓜ', description: 'symbols m maker'},
                {icon: '🆕', description: 'symbols new'},
                {icon: '🆖', description: 'symbols ng'},
                {icon: '🅾️', description: 'symbols o'},
                {icon: '‼', description: 'symbols'},
                {icon: '🔟', description: 'symbols 10'},
                {icon: '💯', description: 'symbols 100'},
                {icon: '🔠', description: 'symbols'},
                {icon: '🔡', description: 'symbols'},
                {icon: '🔢', description: 'symbols'},
                {icon: '🔣', description: 'symbols'},
                {icon: '🔤', description: 'symbols'},
                {icon: '🅰️', description: 'symbols'},
                {icon: '🅰', description: 'symbols'},
                {icon: '🆎', description: 'symbols'},
                {icon: '🅱️', description: 'symbols'},
                {icon: '🅱', description: 'symbols'},
                {icon: '🆑', description: 'symbols'},
                {icon: '🆒', description: 'symbols'},
                {icon: '🆓', description: 'symbols'},
                {icon: 'ℹ', description: 'symbols'},
                {icon: '🆔', description: 'symbols'},
                {icon: 'Ⓜ', description: 'symbols'},
                {icon: '🆕', description: 'symbols'},
                {icon: '🆖', description: 'symbols'},
                {icon: '🅾', description: 'symbols'},
                {icon: '🆗', description: 'symbols'},
                {icon: '🅿️', description: 'symbols'},
                {icon: '🅿', description: 'symbols'},
                {icon: '🆘', description: 'symbols'},
                {icon: '🆙', description: 'symbols'},
                {icon: '🆚', description: 'symbols'},
                {icon: '🈁', description: 'symbols'},
                {icon: '🈂️', description: 'symbols'},
                {icon: '🈶', description: 'symbols'},
                {icon: '🉐', description: 'symbols'},
                {icon: '🈹', description: 'symbols'},
                {icon: '🈚', description: 'symbols'},
                {icon: '🈲', description: 'symbols'},
                {icon: '🉑', description: 'symbols'},
                {icon: '🈸', description: 'symbols'},
                {icon: '🈴', description: 'symbols'},
                {icon: '🈳', description: 'symbols'},
                {icon: '㊗', description: 'symbols'},
                {icon: '㊙', description: 'symbols'},
                {icon: '🈺', description: 'symbols'},
                {icon: '🈵', description: 'symbols'},
                {icon: '▪', description: 'symbols'},
                {icon: '▫', description: 'symbols'},
                {icon: '◻', description: 'symbols'},
                {icon: '◼', description: 'symbols'},
                {icon: '◽', description: 'symbols'},
                {icon: '◾', description: 'symbols'},
                {icon: '⬛', description: 'symbols rectangular geometry'},
                {icon: '⬜', description: 'symbols rectangular'},
                {icon: '🔶', description: 'symbols geometry'},
                {icon: '🔷', description: 'symbols geometry'},
                {icon: '🔸', description: 'symbols geometry'},
                {icon: '🔹', description: 'symbols geometry'},
                {icon: '🔺', description: 'symbols geometry'},
                {icon: '🔻', description: 'symbols'},
                {icon: '💠', description: 'symbols'},
                {icon: '🔘', description: 'symbols'},
                {icon: '🔲', description: 'symbols'},
                {icon: '🔳', description: 'symbols circle round'},
                {icon: '⚪', description: 'symbols circle round'},
                {icon: '⚫', description: 'symbols circle round'},
                {icon: '⚫', description: 'symbols circle round'},
                {icon: '🔴', description: 'symbols circle round'},
                {icon: '🔵', description: 'symbols circle round'},

            ]
        },
        {
            title: 'Flags',
            icon: '🏁',
            data: [
                {icon: '🏁', description: 'flags'},
                {icon: '🇨🇳', description: 'flags'},
                {icon: '🎌', description: 'flags'},
                {icon: '🇩🇪', description: 'de flags'},
                {icon: '🇪🇸', description: 'es flags'},
                {icon: '🇦🇨', description: 'ac flags'},
                {icon: '🇦🇩', description: 'ad flags'},
                {icon: '🇦🇪', description: 'ae flags'},
                {icon: '🇦🇫', description: 'af flags'},
                {icon: '🇦🇬', description: 'ag flags'},
                {icon: '🇦🇮', description: 'ai flags'},
                {icon: '🇦🇱', description: 'al flags'},
                {icon: '🇦🇲', description: 'am flags'},
                {icon: '🇦🇴', description: 'ao flags'},
                {icon: '🇦🇶', description: 'aq flags'},
                {icon: '🇦🇷', description: 'arflags'},
                {icon: '🇦🇸', description: 'as flags'},
                {icon: '🇦🇹', description: 'at flags'},
                {icon: '🇦🇺', description: 'au flags'},
                {icon: '🇦🇼', description: 'aw flags'},
                {icon: '🇦🇽', description: 'ax flags'},
                {icon: '🇦🇿', description: 'az flags'},
                {icon: '🇧🇦', description: 'ba flags'},
                {icon: '🇧🇧', description: 'bb flags'},
                {icon: '🇧🇩', description: 'bd flags'},
                {icon: '🇧🇪', description: 'be flags'},
                {icon: '🇧🇫', description: 'bf flags'},
                {icon: '🇧🇬', description: 'bg flags'},
                {icon: '🇧🇭', description: 'bh flags'},
                {icon: '🇧🇮', description: 'bi flags'},
                {icon: '🇧🇯', description: 'bj flags'},
                {icon: '🇧🇱', description: 'bl flags'},
                {icon: '🇧🇲', description: 'bm flags'},
                {icon: '🇧🇳', description: 'bn flags'},
                {icon: '🇧🇴', description: 'bo flags'},
                {icon: '🇧🇶', description: 'bq flags'},
                {icon: '🇧🇷', description: 'br flags'},
                {icon: '🇧🇸', description: 'bs flags'},
                {icon: '🇧🇹', description: 'bt flags'},
                {icon: '🇧🇻', description: 'bv flags'},
                {icon: '🇧🇼', description: 'bw flags'},
                {icon: '🇧🇾', description: 'by flags'},
                {icon: '🇧🇿', description: 'bz flags'},
                {icon: '🇨🇦', description: 'ca flags'},
                {icon: '🇨🇨', description: 'cc flags'},
                {icon: '🇨🇩', description: 'cd flags'},
                {icon: '🇨🇫', description: 'cf flags'},
                {icon: '🇨🇬', description: 'cg flags'},
                {icon: '🇨🇭', description: 'ch flags'},
                {icon: '🇨🇮', description: 'ci flags'},
                {icon: '🇨🇰', description: 'ck flags'},
                {icon: '🇨🇱', description: 'cl flags'},
                {icon: '🇨🇲', description: 'cm flags'},
                {icon: '🇨🇴', description: 'co flags'},
                {icon: '🇨🇵', description: 'cp flags'},
                {icon: '🇨🇷', description: 'cr flags'},
                {icon: '🇨🇺', description: 'cu flags'},
                {icon: '🇨🇻', description: 'cv flags'},
                {icon: '🇨🇼', description: 'cw flags'},
                {icon: '🇨🇽', description: 'cx flags'},
                {icon: '🇨🇾', description: 'cy flags'},
                {icon: '🇨🇿', description: 'cz flags'},
                {icon: '🇩🇬', description: 'dg flags'},
                {icon: '🇩🇯', description: 'dj flags'},
                {icon: '🇩🇰', description: 'dk flags'},
                {icon: '🇩🇲', description: 'dm flags'},
                {icon: '🇩🇴', description: 'do flags'},
                {icon: '🇩🇿', description: 'dz flags'},
                {icon: '🇪🇦', description: 'ea flags'},
                {icon: '🇪🇨', description: 'ec flags'},
                {icon: '🇪🇪', description: 'ee flags'},
                {icon: '🏴', description: 'flags'},
                {icon: '🇪🇷', description: 'er flags'},
                {icon: '🇪🇹', description: 'et flags'},
                {icon: '🇪🇺', description: 'eu flags'},
                {icon: '🇫🇮', description: 'fiflags'},
                {icon: '🇫🇯', description: 'fj flags'},
                {icon: '🇫🇰', description: 'fk flags'},
                {icon: '🇫🇲', description: 'fm flags'},
                {icon: '🇫🇴', description: 'fo flags'},
                {icon: '🇬🇦', description: 'ga flags'},
                {icon: '🇬🇩', description: 'gd flags'},
                {icon: '🇬🇪', description: 'ge flags'},
                {icon: '🇬🇫', description: 'gf flags'},
                {icon: '🇬🇬', description: 'gg flags'},
                {icon: '🇬🇭', description: 'gh flags'},
                {icon: '🇬🇮', description: 'gi flags'},
                {icon: '🇬🇱', description: 'gl flags'},
                {icon: '🇬🇲', description: 'gm flags'},
                {icon: '🇬🇳', description: 'gn flags'},
                {icon: '🇬🇵', description: 'gp flags'},
                {icon: '🇬🇶', description: 'gq flags'},
                {icon: '🇬🇷', description: 'gr flags'},
                {icon: '🇬🇸', description: 'gs flags'},
                {icon: '🇬🇹', description: 'gt flags'},
                {icon: '🇬🇺', description: 'gu flags'},
                {icon: '🇬🇼', description: 'gw flags'},
                {icon: '🇬🇾', description: 'gy flags'},
                {icon: '🇭🇰', description: 'hk flags'},
                {icon: '🇭🇲', description: 'hm flags'},
                {icon: '🇭🇳', description: 'hn flags'},
                {icon: '🇭🇷', description: 'hr flags'},
                {icon: '🇭🇹', description: 'ht flags'},
                {icon: '🇭🇺', description: 'hu flags'},
                {icon: '🇮🇨', description: 'ic flags'},
                {icon: '🇮🇩', description: 'id flags'},
                {icon: '🇮🇪', description: 'ie flags'},
                {icon: '🇮🇱', description: 'il flags'},
                {icon: '🇮🇲', description: 'im flags'},
                {icon: '🇮🇳', description: 'in flags'},
                {icon: '🇮🇴', description: 'io flags'},
                {icon: '🇮🇷', description: 'ir flags'},
                {icon: '🇮🇸', description: 'is flags'},
                {icon: '🇯🇪', description: 'je flags'},
                {icon: '🇯🇲', description: 'jm flags'},
                {icon: '🇯🇴', description: 'jo flags'},
                {icon: '🇰🇪', description: 'ke flags'},
                {icon: '🇰🇬', description: 'kg flags'},
                {icon: '🇰🇭', description: 'kh flags'},
                {icon: '🇰🇮', description: 'ki flags'},
                {icon: '🇰🇲', description: 'km flags'},
                {icon: '🇰🇳', description: 'kn flags'},
                {icon: '🇰🇵', description: 'kp flags'},
                {icon: '🇰🇼', description: 'kw flags'},
                {icon: '🇰🇾', description: 'ky flags'},
                {icon: '🇰🇿', description: 'kz flags'},
                {icon: '🇱🇦', description: 'la flags'},
                {icon: '🇱🇧', description: 'lb flags'},
                {icon: '🇱🇨', description: 'lc flags'},
                {icon: '🇱🇮', description: 'li flags'},
                {icon: '🇱🇰', description: 'lk flags'},
                {icon: '🇱🇷', description: 'lr flags'},
                {icon: '🇱🇸', description: 'ls flags'},
                {icon: '🇱🇹', description: 'lt flags'},
                {icon: '🇱🇺', description: 'lu flags'},
                {icon: '🇱🇻', description: 'lv flags'},
                {icon: '🇱🇾', description: 'ly flags'},
                {icon: '🇲🇦', description: 'ma flags'},
                {icon: '🇲🇨', description: 'mc flags'},
                {icon: '🇲🇩', description: 'md flags'},
                {icon: '🇲🇪', description: 'me flags'},
                {icon: '🇲🇫', description: 'mf flags'},
                {icon: '🇲🇬', description: 'mg flags'},
                {icon: '🇲🇭', description: 'mh flags'},
                {icon: '🇲🇰', description: 'mk flags'},
                {icon: '🇲🇱', description: 'ml flags'},
                {icon: '🇲🇲', description: 'mm flags'},
                {icon: '🇲🇳', description: 'mn flags'},
                {icon: '🇲🇴', description: 'mo flags'},
                {icon: '🇲🇵', description: 'mp flags'},
                {icon: '🇲🇶', description: 'mq flags'},
                {icon: '🇲🇷', description: 'mr flags'},
                {icon: '🇲🇷', description: 'mr flags'},
                {icon: '🇲🇸', description: 'ms flags'},
                {icon: '🇲🇹', description: 'mt flags'},
                {icon: '🇲🇺', description: 'mu flags'},
                {icon: '🇲🇻', description: 'mv flags'},
                {icon: '🇲🇼', description: 'mw flags'},
                {icon: '🇲🇽', description: 'mx flags'},
                {icon: '🇲🇾', description: 'my flags'},
                {icon: '🇲🇿', description: 'mz flags'},
                {icon: '🇳🇦', description: 'na flags'},
                {icon: '🇳🇨', description: 'nc flags'},
                {icon: '🇳🇪', description: 'ne flags'},
                {icon: '🇳🇫', description: 'nf flags'},
                {icon: '🇳🇬', description: 'ng flags'},
                {icon: '🇳🇮', description: 'ni flags'},
                {icon: '🇳🇱', description: 'nl flags'},
                {icon: '🇳🇴', description: 'no flags'},
                {icon: '🇳🇵', description: 'np flags'},
                {icon: '🇳🇷', description: 'nr flags'},
                {icon: '🇳🇺', description: 'nu flags'},
                {icon: '🇳🇿', description: 'nz flags'},
                {icon: '🇴🇲', description: 'om flags'},
                {icon: '🇵🇦', description: 'pa flags'},
                {icon: '🇵🇪', description: 'pe flags'},
                {icon: '🇵🇫', description: 'pf flags'},
                {icon: '🇵🇬', description: 'pg flags'},
                {icon: '🇵🇭', description: 'ph flags'},
                {icon: '🇵🇰', description: 'pk flags'},
                {icon: '🇵🇱', description: 'pl flags'},
                {icon: '🇵🇲', description: 'pm flags'},
                {icon: '🇵🇳', description: 'pn flags'},
                {icon: '🇵🇷', description: 'pr flags'},
                {icon: '🇵🇸', description: 'ps flags'},
                {icon: '🇵🇹', description: 'pt flags'},
                {icon: '🇵🇼', description: 'pw flags'},
                {icon: '🇵🇾', description: 'py flags'},
                {icon: '🇶🇦', description: 'qa flags'},
                {icon: '🇷🇪', description: ' re flags'},
                {icon: '🇷🇴', description: 'ro flags'},
                {icon: '🇷🇸', description: 'rs flags'},
                {icon: '🇷🇼', description: 'rw flags'},
                {icon: '🇸🇦', description: 'sa flags'},
                {icon: '🇸🇧', description: 'sb flags'},
                {icon: '🇸🇨', description: 'sc flags'},
                {icon: '🏴', description: 'flags'},
                {icon: '🇸🇩', description: 'sd flags'},
                {icon: '🇸🇪', description: 'se flags'},
                {icon: '🇸🇬', description: 'sg flags'},
                {icon: '🇸🇭', description: 'sh flags'},
                {icon: '🇸🇮', description: 'si flags'},
                {icon: '🇸🇯', description: 'sjflags'},
                {icon: '🇸🇰', description: 'sk flags'},
                {icon: '🇸🇱', description: 'sl flags'},
                {icon: '🇸🇲', description: 'sm flags'},
                {icon: '🇸🇳', description: 'sn flags'},
                {icon: '🇸🇴', description: 'so flags'},
                {icon: '🇸🇷', description: 'sr flags'},
                {icon: '🇸🇸', description: 'ss flags'},
                {icon: '🇸🇹', description: 'st flags'},
                {icon: '🇸🇻', description: 'sv flags'},
                {icon: '🇸🇽', description: 'sx flags'},
                {icon: '🇸🇾', description: 'sy flags'},
                {icon: '🇸🇿', description: 'sz flags'},
                {icon: '🇹🇦', description: 'ta flags'},
                {icon: '🇹🇨', description: 'tc flags'},
                {icon: '🇹🇩', description: 'td flags'},
                {icon: '🇹🇫', description: 'tf flags'},
                {icon: '🇹🇬', description: 'tg flags'},
                {icon: '🇹🇭', description: 'th flags'},
                {icon: '🇹🇯', description: 'tj flags'},
                {icon: '🇹🇰', description: 'tk flags'},
                {icon: '🇹🇱', description: 'tl flags'},
                {icon: '🇹🇲', description: 'tm flags'},
                {icon: '🇹🇳', description: 'tn flags'},
                {icon: '🇹🇴', description: 'to flags'},
                {icon: '🇹🇷', description: 'tr flags'},
                {icon: '🇹🇹', description: 'tt flags'},
                {icon: '🇹🇻', description: 'tvflags'},
                {icon: '🇹🇼', description: 'tw flags'},
                {icon: '🇹🇿', description: 'tz flags'},
                {icon: '🇺🇦', description: 'ua flags'},
                {icon: '🇺🇬', description: 'ug flags'},
                {icon: '🇺🇲', description: 'um flags'},
                {icon: '🇺🇾', description: 'uy flags'},
                {icon: '🇺🇿', description: 'uz flags'},
                {icon: '🇻🇦', description: 'va flags'},
                {icon: '🇻🇨', description: 'vc flags'},
                {icon: '🇻🇪', description: 've flags'},
                {icon: '🇻🇬', description: 'vg flags'},
                {icon: '🇻🇮', description: 'vi flags'},
                {icon: '🇻🇳', description: 'vn flags'},
                {icon: '🇻🇺', description: 'vu flags'},
                {icon: '🏴', description: 'flags'},
                {icon: '🇼🇫', description: 'wf flags'},
                {icon: '🇼🇸', description: 'ws flags'},
                {icon: '🇽🇰', description: 'xk flags'},
                {icon: '🇾🇪', description: 'ye flags'},
                {icon: '🇾🇹', description: 'yt flags'},
                {icon: '🇿🇦', description: 'za flags'},
                {icon: '🇿🇲', description: 'zm flags'},
                {icon: '🇿🇼', description: 'zw flags'},
                {icon: '🇫🇷', description: 'fr flags'},
                {icon: '🇬🇧', description: 'gb flags'},
                {icon: '🇮🇹', description: 'it flags'},
                {icon: '🇯🇵', description: 'jp flags'},
                {icon: '🇰🇷', description: 'kr flags'},
                {icon: '🏳️', description: 'flags'},
                {icon: '‍🌈', description: 'flags'},
                {icon: '🇷🇺', description: 'ru flags'},
                {icon: '🚩', description: 'flags'},
                {icon: '🇺🇸', description: 'us flags'},
                {icon: '🏴', description: 'flags'},
                {icon: '🏳️', description: 'flags'},

            ]
        },
    ]
};
export const emojiService = service;
